FROM bellsoft/liberica-openjdk-alpine:11.0.16 as BuildProject
WORKDIR /app
COPY ./src ./src
RUN mkdir ./out
RUN javac -sourcepath ./src -d out ./src/ru/gb/hw1/sample/Main.java
CMD java -classpath ./out ru.gb.hw1.sample.Main

FROM scratch as OutputFiles
COPY --from=BuildProject /app/out /bin
